# Generated by Django 5.1.1 on 2024-09-19 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('stream', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.SmallIntegerField()),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='school.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='school.parents')),
                ('results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.grades')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='school.classes')),
                ('subjects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='school.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='parents',
            name='child',
            field=models.ManyToManyField(to='school.students'),
        ),
        migrations.AddField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='school.students'),
        ),
    ]
