# Generated by Django 5.1.1 on 2024-09-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(blank=True, max_length=100, null=True)),
                ('average', models.SmallIntegerField()),
            ],
        ),
    ]
