# Generated by Django 5.1.1 on 2024-09-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_rename_books_book_rename_requests_request'),
        ('school', '0003_stream_alter_classes_stream'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Class',
        ),
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('child', models.ManyToManyField(related_name='parents', to='school.student')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='school.parent'),
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
