# Generated by Django 5.1.1 on 2024-09-26 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_classes_class_rename_grades_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.stream', unique=True),
        ),
    ]
