# Generated by Django 5.1.1 on 2024-09-26 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_class_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='stream',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='school.stream'),
        ),
    ]
