# Generated by Django 5.1.1 on 2024-09-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_class_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='stream',
        ),
        migrations.AlterField(
            model_name='stream',
            name='letter',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='class',
            name='stream',
            field=models.ManyToManyField(to='school.stream'),
        ),
    ]
