# Generated by Django 5.1.1 on 2024-09-26 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_class_stream_alter_stream_letter_class_stream'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('number', 'stream')},
        ),
        migrations.AlterField(
            model_name='stream',
            name='letter',
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name='class',
            name='stream',
        ),
        migrations.AddField(
            model_name='class',
            name='stream',
            field=models.ForeignKey(default='Nil', on_delete=django.db.models.deletion.PROTECT, to='school.stream'),
        ),
    ]
